namespace: kafka
serviceName: kafka-service
replica: 1
headlessName: kafka-headless

env_vars:
  nodeId: "1"
  kafka_listeners: INTERNAL://:9092,EXTERNAL://:9094,CONTROLLER://:9093
  kafka_adv_listeners: EXTERNAL://192.168.1.77:30030,INTERNAL://kafka-headless.kafka:9092
  kafka_inter_broker_listener_name: INTERNAL
  kafka_listener_security_protocol_map: EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT
  kafka_controller_quorum_voters: "1@kafka-headless.kafka:9093"
  kafka_num_partitions: "1"
  kafka_offsets_topic_replication_factor: "1"
  kafka_auto_create_topics_enable: "true"
  kafka_offsets_topic_num_partitions: "10"
  kafka_controller_listener_names: "CONTROLLER"
  allow_plaintext_listener: "yes"

volumeMounts:
  name: kafka-data
  mountPath: /var/lib/kafka/data

nodePort: 30030
