apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "kafka-infra.fullname" . }}
  namespace: {{ .Values.namespace }}

spec:
  serviceName: {{ .Values.serviceName }}
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ include "kafka-infra.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "kafka-infra.fullname" . }}
    spec:
      containers:
        - name: {{ include "kafka-infra.fullname" . }}
          image: apache/kafka:3.7.0
          env:
            - name: KAFKA_PROCESS_ROLES
              value: broker,controller
          {{- range $key, $value := .Values.env_vars }}
            - name: {{ $key }}
              value: {{ $value | quote }}
          {{- end }}
          ports:
            - containerPort: 9092
          volumeMounts:
            - name: {{ .Values.volumeMounts.name }}
              mountPath: {{ .Values.volumeMounts.mountPath }}

  volumeClaimTemplates:
    - metadata:
        name: {{ .Values.volumeMounts.name }}
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: local-path
        resources:
          requests:
            storage: 10Gi
