apiVersion: v1
kind: Service
metadata:
  name: vault-ui
  namespace: vault
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: vault
    app.kubernetes.io/component: server
  ports:
    - port: 8200         # Vault port
      targetPort: 8200
