apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nextjs-service.fullname" . }}
  labels:
    app: {{ include "nextjs-service.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "nextjs-service.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "nextjs-service.name" . }}
    spec:
      # Pull secret for private ECR
      imagePullSecrets:
        {{- range .Values.image.pullSecrets }}
        - name: {{ .name }}
        {{- end }}
      containers:
        - name: {{ include "nextjs-service.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3000
          env:
            - name: ENVIRONMENT
              value: "{{ .Values.env.ENVIRONMENT }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
