apiVersion: v1
kind: Service
metadata:
  name: {{ include "lan-dashboard.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "lan-dashboard.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      nodePort: {{ .Values.service.nodePort | default 30080 }}
