apiVersion: v1
kind: Service
metadata:
  name: {{ include "nextjs-service.fullname" . }}
spec:
  selector:
    app: {{ include "nextjs-service.name" . }}
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
