replicaCount: 2

image:
  repository: 387555629933.dkr.ecr.us-east-1.amazonaws.com/kafka-consumer
  tag: 0.0.3
  pullPolicy: IfNotPresent
  pullSecrets:
    - name: ecr-registry


ingress:
  name: consumer-test-ingress
  host: consumer.svc.local

serviceAccount:
  name: myapp-sa

vault:
  role: consumer-role
  secretPath: kv/data/kafka-consumer

nodeSelector: {}
tolerations: []
affinity: {}
