replicaCount: 2

image:
  repository: 387555629933.dkr.ecr.us-east-1.amazonaws.com/kafka-consumer
  tag: 0.0.1
  pullPolicy: IfNotPresent


ingress:
  name: fastapi-test-ingress
  host: fastapi.svc.local

serviceAccount:
  name: myapp-sa

vault:
  role: consumer-role
  secretPath: kv/data/lan-dashboard

nodeSelector: {}
tolerations: []
affinity: {}
