apiVersion: v1
kind: ConfigMap
metadata:
  name: flink-config
data:
  flink-conf.yaml: |
    jobmanager.rpc.address: flink-jobmanager
    taskmanager.numberOfTaskSlots: 2
    parallelism.default: 2

    rest.port: 8081
    rest.address: 0.0.0.0
    rest.bind-address: 0.0.0.0

    # Enable jar upload
    web.submit.enable: true

    # Blob storage
    blob.server.port: 6124

    # State backend example
    state.backend: hashmap

    jobmanager.memory.process.size: 1024m
    taskmanager.memory.process.size: 2048m
