server:
  ha:
    enabled: true
    replicas: 1

    raft:
      enabled: true
      path: /vault/data
      setNodeId: true


  dataStorage:
    enabled: true
    size: 10Gi
    mountPath: /vault/data
    storageClass: local-path
    accessMode: ReadWriteOnce
ui:
  enabled: true

service:
  enabled: true
  type: ClusterIP
