
apiVersion: v1
kind: Pod
metadata:
  name: hostpath-pod
spec:
  volumes:
  - name: hostpath-vol
    hostPath:
      path: /home/vector_tensor/path
  containers:
  - name: hostpath-pod
    image: 'registry.k8s.io/e2e-test-images/busybox:1.29-4'
    command: 
      - /bin/sh
      - -c
      - |
        echo "Hello Team, This is Sample File for HostVolume - $(date)" >> /output/output.txt
        sleep 86400
    volumeMounts:
    - name: hostpath-vol
      mountPath: /output
